// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi0sfJzTPKkYOP0kacRokjB_k8XPp7tuc',
    appId: '1:737881985527:web:f207cb91fc3794ebd9def2',
    messagingSenderId: '737881985527',
    projectId: 'mynotes-flutter-wile44',
    authDomain: 'mynotes-flutter-wile44.firebaseapp.com',
    storageBucket: 'mynotes-flutter-wile44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmoSAF8B4gHqrwLDQgxr8JOLecU-ujnX4',
    appId: '1:737881985527:android:c9a521b807deb336d9def2',
    messagingSenderId: '737881985527',
    projectId: 'mynotes-flutter-wile44',
    storageBucket: 'mynotes-flutter-wile44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ3TA7uLJF7zxeazP2Mf9VvGkZ1mu3Qvg',
    appId: '1:737881985527:ios:86ee0b31d157c7a2d9def2',
    messagingSenderId: '737881985527',
    projectId: 'mynotes-flutter-wile44',
    storageBucket: 'mynotes-flutter-wile44.appspot.com',
    iosClientId: '737881985527-23146e7tvi32s1p32df2u7q5majn3i86.apps.googleusercontent.com',
    iosBundleId: 'com.goodluckwile.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ3TA7uLJF7zxeazP2Mf9VvGkZ1mu3Qvg',
    appId: '1:737881985527:ios:86ee0b31d157c7a2d9def2',
    messagingSenderId: '737881985527',
    projectId: 'mynotes-flutter-wile44',
    storageBucket: 'mynotes-flutter-wile44.appspot.com',
    iosClientId: '737881985527-23146e7tvi32s1p32df2u7q5majn3i86.apps.googleusercontent.com',
    iosBundleId: 'com.goodluckwile.mynotes',
  );
}
